# This file was generated by GoReleaser. DO NOT EDIT.
cask "config" do
  version "0.23.0"

  on_macos do
    on_arm do
      sha256 "922072442db12c1323e087ca1388793ddbafa091467ec400f99d5c2c608edd03"
      url "https://github.com/azohra/config/releases/download/v#{version}/config_darwin_arm64.tar.gz"
    end
  end

  name "config"
  desc "Converge machine configuration from a Git repository"
  homepage "https://github.com/azohra/config"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "config"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/config"]
  end

  # No zap stanza required
end
