# This file was generated by GoReleaser. DO NOT EDIT.
cask "config" do
  version "0.24.1"

  on_macos do
    on_arm do
      sha256 "d0d63134bb509cfa106318331c2cdd1fedb8a9415c13e983fd7dca8eb4f65f4d"
      url "https://github.com/azohra/config/releases/download/v#{version}/config_darwin_arm64.tar.gz"
    end
  end

  name "config"
  desc "Converge machine configuration from a Git repository"
  homepage "https://github.com/azohra/config"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "config"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/config"]
  end

  # No zap stanza required
end
